services:
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "sed -i 's/\r$//' bin/* && chmod +x bin/* && bundle exec rails db:prepare && bundle exec rails server -b 0.0.0.0"
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    environment:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres_password
      DATABASE_HOST: db
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: